### PR TITLE
Fixed an issue where variables can not be used in effects.

### PR DESCRIPTION
**Pull request by IceLitty**

### CODE REVIEW

**Comment by IceLitty** [comment]
The URL of your Residence.jar should be changed, at the moment I use http://ltcraft.lt/Residence/download.php?file=Residence4.5.3.0.jar

**Comment by TheComputerGeek2** [comment]
While I think this is a great change, I feel that the implementation of this concept needs a few tweaks. The main concern I have with this is that the text content of the effect will differ based upon who views the effect rather than who casts the effect. If you have any questions or points you'd like to discuss, feel free to either respond here or join the discord linked in the readme file of this project.

**Comment by IceLitty** [comment]
Oh, I don't know how to use github. Is it because the pull hasn't passed yet, so my update in my fork project will automatically pull into this request? In addition, how to keep the fork project synchronized, pull the original project into the fork project? Always feel some problems...

The content of these follow-up updates is a self-use passive skills triggers, based on the `rightclickblocktype` rewrite, after the player right-click the block, centered on the block coordinates, radius to specify the number of grids, identify items and amount meet the requirements, the final run skills

**Comment by IceLitty** [comment]
Regarding your previous question, I only applied %t instead of %a, because the player obtained here is actually the player who sees this effect. Of course, this is also true for %var.

**Comment by TheComputerGeek2** [comment]
@IceLitty It would be easier to explain via discord, if possible, could you join me (and the majority of the community) on [here](https://discord.gg/FJXfDPZ) (the community Discord)? It would also be overall easier to coordinate with regards to any future changes.

**Pull request closed without merging**
